sudo: false
language: node_js
node_js:
  - '8'
before_deploy: "npm run build"
deploy:
  provider: npm
  email: "zhouzhi073859@outlook.com"
  api_key: "0e92209c-52fa-4beb-a0c0-72478c9cd0cf"
  on:
    branch: master
